### ISSUE TITLE
Can't compile on OF073 on a 10.6.8 system ...

### ISSUE THREAD

**Issue by eloimaduell** [paulobarcelos/ofxMacamPs3Eye#3]
hi Paulo ! 

i'm Eloi Maduell ... OF belover from Barcelona .
i've trying to compile and test the "example-gui" example from ofxMacamPs3Eye but can't make it work.
I'm compiling it with XCode 3.2.4 on a 10.6.8 Snow Leopard laptop ... with OF073 ...

the errors i got on compilation are:

/example-gui/../../../addons/ofxMacamPs3Eye/src/PS3EyeWindowAppDelegate.h:48: error: unknown property attribute
/example-gui/../../../addons/ofxMacamPs3Eye/src/PS3EyeWindowAppDelegate.h:48: error: syntax error in @property's attribute declaration
/example-gui/../../../addons/ofxMacamPs3Eye/src/ofxMacamPs3Eye.mm: In member function 'virtual void ofxMacamPs3Eye::setDeviceID(int)':
/example-gui/../../../addons/ofxMacamPs3Eye/src/ofxMacamPs3Eye.mm:53: error: expected unqualified-id before '=' token
/example-gui/../../../addons/ofxMacamPs3Eye/src/ofxMacamPs3Eye.mm:54: error: expected unqualified-id before '=' token

Any idea of what i'm doing wrong ? 
Thanks for your support .

e*
