### ISSUE TITLE
GenericDriver.m fails building with SDK newer than 10.6

### ISSUE THREAD

**Issue by madc** [paulobarcelos/ofxMacamPs3Eye#4]
I am on the current master brunch of OF and ofxMacamPs3Eye and using Xcode 4.5.2 on OSX 10.7.
It compiles fine with the SDK 10.6, but Xcode 4.5 removed the native support for SDKs older than 10.7.

```
/Users/me/Projects/Development/openFrameworks/addons/ofxMacamPs3Eye/src/macam/GenericDriver.m:1904:5: Use of undeclared identifier 'GetGWorld'
/Users/me/Projects/Development/openFrameworks/addons/ofxMacamPs3Eye/src/macam/GenericDriver.m:1905:5: Use of undeclared identifier 'SetGWorld'
/Users/me/Projects/Development/openFrameworks/addons/ofxMacamPs3Eye/src/macam/GenericDriver.m:1909:27: Use of undeclared identifier 'GetGWorldPixMap'
/Users/me/Projects/Development/openFrameworks/addons/ofxMacamPs3Eye/src/macam/GenericDriver.m:1914:5: Use of undeclared identifier 'SetGWorld'
/Users/me/Projects/Development/openFrameworks/addons/ofxMacamPs3Eye/src/macam/GenericDriver.m:1915:5: Use of undeclared identifier 'DisposeGWorld'
/Users/me/Projects/Development/openFrameworks/addons/ofxMacamPs3Eye/src/macam/GenericDriver.m:1941:40: Use of undeclared identifier 'GetGWorldPixMap
```
